Repository devugees/digital-notice-board, pull requests merged in 2018-03, with the labels that each got.

#2 Travis ci
  .travis.yml
  README.md
  package-lock.json
  package.json
  tests/sum.js
  tests/sum.test.js
Labels: in progress

#35 Feature/listofslidescomponent
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
  frontend/src/index.js
  package-lock.json
Labels: in progress

#45 Feature/video/add video
  frontend/src/App.js
  frontend/src/components/video/AddVideo.js
  frontend/yarn.lock
  yarn-error.log
  yarn.lock
Labels: in progress

#44 mock forgot password form
  frontend/src/App.js
  frontend/src/components/forgot/ForgotPassword.css
  frontend/src/components/forgot/ForgotPassword.js
Labels: in progress

#42 Feature/option component
  frontend/src/components/Option.js
  frontend/src/components/video/Video.test.js
Labels: in progress

#52 Feature/video/add video
  frontend/src/App.js
  frontend/src/components/AddVideo/AddVideo.js
  frontend/yarn.lock
Labels: in progress

#50 Feature/setup jest testing
  .travis.yml
  frontend/.babelrc
  frontend/__mocks__/fileMock.js
  frontend/__mocks__/styleMock.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.js
  frontend/tests/sum.js
  frontend/tests/sum.test.js
Labels: in progress, testing team

#47 Login Component
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/Login.js
Labels: in progress

#53 Feature/listofslidescomponent
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
Labels: code review

#57 Feature/option update
  frontend/src/components/Option.js
Labels: in progress

#62 POST Request sent
  frontend/src/Login.js
Labels: in progress

#69 Feature/css grid2
  backend/package-lock.json
  backend/package.json
  backend/server/temp.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/SlideAnnouncement.js
  frontend/src/components/SlideCode.js
  frontend/src/components/SlidePhotos.js
  frontend/src/components/SlideVideo.js
  frontend/src/components/video/Video.css
  frontend/src/components/video/Video.js
  frontend/src/components/video/VideoDescription.css
  frontend/src/components/video/VideoDescription.js
  frontend/src/constants/icons.js
  frontend/src/constants/slideTypes.js
  frontend/src/mockcss.html
  package-lock.json
Labels: in progress

#65 Embeding video and stop event listener
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/video/Video.js
Labels: code review

#70 Feature/video/add video
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#73 Changed classNames in label AddVideo, added anchor tag for deleteing functionality
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#72 Feature/slide timeline Reactstrap installed in terminal
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Login/Login.js
  frontend/src/components/timeline/SlideTimeline.js
  frontend/src/constants/misc.js
  frontend/src/index.js
Labels: in progress

#79 moved the components in folders
  frontend/src/components/Login/Login.js
Labels: in progress

#83 Feature/video/add video
  frontend/src/components/AddVideo/AddVideo.js
  frontend/src/components/Click-Func.js
Labels: in progress

#80 Feature/listofslidescomponent
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
Labels: in progress

#84 Feature/video/add video
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#90 Feature/video/add video
  frontend/src/components/AddVideo/AddVideo.js
  frontend/yarn.lock
Labels: in progress

#96 slide timeline progressbar fixed
  frontend/src/components/timeline/SlideTimeline.js
Labels: in progress

#100 routes created
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Route/Router.js
  frontend/src/index.js
Labels: in progress

#99 Feature/create test for add video component
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AddVideo/AddVideo.js
  frontend/src/components/AddVideo/AddVideo.test.js
Labels: in progress

#101 fixed forgot password component
  frontend/src/components/forgot/ForgotPassword.js
Labels: in progress

#102 Feature/signup css jsx
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Register/Register.js
Labels: in progress

#104 setting up icon fonts for the symbol on the slides
  frontend/public/index.html
  frontend/src/mockcss.html
Labels: in progress

#103 Feature/date format
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#106 changed link from admin into login
  frontend/src/components/forgot/ForgotPassword.js
Labels: in progress

#107 Feature/createjsx css for code snippetslide
  frontend/public/code-snippets/pic1.png
  frontend/public/code-snippets/pic2.png
  frontend/src/App.js
  frontend/src/components/snippet-slide/SnippetSlide.js
  frontend/src/components/timeline/SlideTimeline.js
Labels: in progress

#109 Feature/css grid2
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/mockcss.html
Labels: in progress

#111 email validation func
  frontend/src/components/Login/Login.js
Labels: in progress

#112 Feature/video/add video
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#117 Feature/create test for add video component
  frontend/package-lock.json
Labels: in progress

#118 Feature/module sidebar click handler
  frontend/src/App.js
  frontend/src/components/codeSnippetSlide/CodeSnippetSlide.js
  frontend/src/components/codeSnippetSlide/CodeSnippetSlide.test.js
  frontend/src/components/login/Login.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
  package-lock.json
Labels: in progress

#105 Feature/backend user
  .gitignore
  backend/.env
  backend/_env_schema
  backend/package-lock.json
  backend/package.json
  backend/server/config/passport.js
  backend/server/index.js
  backend/server/mockup/mockup.json
  backend/server/models/content.js
  backend/server/models/user.js
  backend/server/routes/admin.js
  backend/server/routes/users.js
Labels: in progress

#123 Created all the functionality in Register Component
  frontend/src/components/Register/Register.js
Labels: in progress

#125 delete the if statement from SlideTimeLine
  frontend/src/components/modules-side-bar/ModulesSideBar.js
Labels: in progress

#126 Feature/video/add video refactor
  frontend/src/App.js
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#127 AdminPage created
  backend/package-lock.json
  backend/server/index.js
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/Search.js
  frontend/src/components/Admin/SlideDetail.js
  frontend/src/components/Route/Router.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
Labels: in progress

#129 Release/connect backend to frontend
  README.md
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/Admin/Admin.js
  package-lock.json
Labels: in progress

#134 Feature/create jsx css for photo silde
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/photos/Photos.css
  frontend/src/components/photos/Photos.js
  frontend/src/components/photos/slides.js
Labels: in progress

#138 Feature/backend user
  backend/package-lock.json
  backend/package.json
  backend/server/models/content.js
  backend/server/routes/admin.js
  backend/server/routes/mailnotifier.js
  backend/server/routes/users.js
  backend/server/routes/youtube.js
  backend/yarn.lock
Labels: in progress

#141 VIdeos and Slide Design
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
  frontend/src/components/video/Video.js
Labels: in progress

#144 forget and reset password endpoint
  backend/server/models/user.js
  backend/server/routes/users.js
Labels: in progress

#146 Feature/switching modules in frontend
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.js
  frontend/src/components/snippet-slide/SnippetSlide.js
Labels: code review

#145 Feature/create test for add video component
  frontend/src/components/AddVideo/AddVideo.test.js
  frontend/src/components/AddVideo/__snapshots__/AddVideo.test.js.snap
Labels: code review

#147 Feature/test modules side bar
  frontend/package.json
  frontend/src/components/modules-side-bar/ModulesSideBar.test.js
  frontend/yarn.lock
Labels: in progress

#149 Feature/edit slide
  backend/server/routes/admin.js
Labels: in progress

#151 Feature/backend forget password
  backend/server/routes/users.js
Labels: in progress

#153 Feature/admin home route
  backend/server/routes/admin.js
Labels: in progress

#157 Feature/fix width&height video
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/video/Video.js
Labels: in progress

#152 Feature/frontend routing
  backend/package-lock.json
  backend/server/routes/admin.js
  backend/server/routes/users.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Register/Register.js
  frontend/src/components/Route/Router.js
  frontend/src/components/forgot/ForgotPassword.css
  frontend/src/components/forgot/ForgotPassword.js
  frontend/src/components/login/Login.js
  frontend/src/components/login/style.css
  frontend/src/index.js
Labels: in progress

#158 better conditional rendering
  frontend/src/App.js
Labels: in progress
