Repository devugees/digital-notice-board, pull requests merged in 2018-04, with the labels that each got.

#177 fixed folder naming
  frontend/src/App.js
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Route/Router.js
  frontend/src/components/github/Github.js
  frontend/src/components/github/style.css
  frontend/src/index.js
Labels: code review

#179 #173 Added DCI Favicon
  frontend/public/cropped-logo-32x32.png
  frontend/public/index.html
  frontend/src/App.js
Labels: in progress

#185 fill photos with real photos
  frontend/src/App.js
  frontend/src/components/photos/Photos.css
  frontend/src/components/photos/Photos.js
  frontend/src/components/photos/slides.js
Labels: in progress

#187 added default case for switch statement
  frontend/src/constants/icons.js
Labels: in progress

#182 Feature/replace list group to module side bar component
  frontend/src/components/modules-side-bar/ModulesSideBar.js
Labels: in progress

#189 deleted unused files (incl. Click-Func.js)
  frontend/src/components/Click-Func.js
  frontend/src/components/SlideAnnouncement.js
  frontend/src/components/SlideCode.js
  frontend/src/components/SlidePhotos.js
  frontend/src/components/SlideVideo.js
  frontend/src/mockcss.html
Labels: in progress

#181 Feature/add code
  frontend/src/components/AddCode/AddCode.js
  frontend/src/components/Admin/Admin.js
Labels: code review

#200 feature/optimize-warnings-appjs
  frontend/src/App.js
Labels: code review

#202 Feature/optimize add video validation
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#199 Feature/use icon constants in modulesidebar
  frontend/src/components/modules-side-bar/ModulesSideBar.js
  frontend/src/constants/icons.js
  frontend/src/constants/slideTypes.js
Labels: code review

#201 Feature/create admin type announcement edit component
  frontend/src/components/AddAnnouncement/AddAnnouncement.js
  frontend/src/components/Admin/Admin.js
Labels: in progress

#192 Feature/style admin module sidebarsearch
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/Search.js
Labels: code review, css team

#209 Feature/style login register forgot components
  frontend/src/components/Navigation/Navigation.js
  frontend/src/components/Register/Register.js
  frontend/src/components/forgot/ForgotPassword.js
  frontend/src/components/login/Login.js
Labels: in progress

#212 Feature/create admin type photos edit component
  frontend/src/components/AddPhoto/AddPhoto.js
  frontend/src/components/Admin/Admin.js
Labels: in progress

#211 Feature/video progress bar not reflecting waiting until video ends
  frontend/src/App.js
  frontend/src/components/photos/Photos.css
  frontend/src/components/timeline/SlideTimeline.js
  frontend/src/components/video/Video.js
Labels: in progress

#213 add or edit code slide, admin navigation bar, wire backend
  backend/server/index.js
  backend/server/models/content.js
  backend/server/routes/admin.js
  frontend/src/components/AddCode/AddCode.js
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/AdminNavigation.js
Labels: in progress

#224 Feature/backend announcement should receive new fields from the database
  frontend/src/components/AddAnnouncement/AddAnnouncement.js
Labels: in progress

#231 fixed all errors to addAnnouncement and announcement
  frontend/src/components/AddAnnouncement/AddAnnouncement.js
  frontend/src/components/Announcement/Announcement.js
Labels: in progress

#232 Feature/frontend announcement use fields from database
  frontend/src/components/Announcement/Announcement.js
Labels: in progress

#222 remove SlideDetail Proptypes Importing
  frontend/src/components/Admin/SlideDetail.js
Labels: in progress

#230 Feature/create snippetslidecss and fix highlighting
  frontend/src/App.css
  frontend/src/components/snippet-slide/SnippetSlide.css
  frontend/src/components/snippet-slide/SnippetSlide.js
Labels: in progress

#234 Feature/improve module sidebar display frontend
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/modules-side-bar/ModulesSideBar.css
Labels: in progress

#237 deleted mockslide.html
  frontend/src/mockcodeslide.html
Labels: in progress

#239 added max-width to photos.css
  frontend/src/components/photos/Photos.css
Labels: code review

#242 changed css grid to flex!
  frontend/src/App.css
  frontend/src/App.js
Labels: in progress

#246 Filter Slides by searchfield
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/Search.js
Labels: in progress

#245 fixed height / bg color for left column (slide component)
  frontend/src/App.css
  frontend/src/components/Announcement/Announcement.css
  frontend/src/components/Announcement/Announcement.js
  frontend/src/components/modules-side-bar/ModulesSideBar.css
  frontend/src/components/photos/Photos.css
  frontend/src/components/snippet-slide/SnippetSlide.css
  frontend/src/components/snippet-slide/SnippetSlide.js
  frontend/src/components/timeline/SlideTimeline.css
  frontend/src/components/timeline/SlideTimeline.js
  frontend/src/components/video/Video.js
Labels: code review

#241 Feautre/add videoform has duplicate fields
  frontend/src/components/AddVideo/AddVideo.js
Labels: in progress

#248 scoping to differentiate frontend and backend on css
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Admin/Admin.js
Labels: in progress

#249 Feature/concurrently
  package.json
Labels: in progress

#252 Feature/create meetup backend component
  frontend/src/App.js
  frontend/src/components/meetup/Meetup.js
  frontend/src/constants/icons.js
  frontend/src/constants/slideTypes.js
Labels: in progress

#251 Feature/youtube uses data from backend
  frontend/src/App.js
  frontend/src/components/video/Video.js
Labels: in progress
